---
- hosts: targetHosts
  tasks:
    - name: Make destination folder
      file:
        path: "/home/{{ ansible_user_id }}/backups/backup_{{ ansible_date_time.date }}"
        state: directory
    - name: Copy current files
      copy:
        src: "/home/{{ ansible_user_id }}/gophish/{{ item }}"
        dest: "/home/{{ ansible_user_id }}/backups/backup_{{ ansible_date_time.date }}"
      with_items: ["gophish.db","config.json"]
    - name: Find backup directories
      find:
        paths: /home/{{ ansible_user_id }}/backups/
        file_type: directory
      register: return
    - name: Delete oldest directory
      file:
        path: "{{return.files[0].path}}"
        state: absent
      when: return.files | length > 4
